### ISSUE TITLE
Update repo url

### ISSUE THREAD

**Issue by vany0114** [mjebrahimi/Awesome-Microservices-NetCore#2]
Hi guys @coskun @mjebrahimi ,

First things first, thanks so much for sharing this, is awesome and really helpful for all people out there interested in microservices and .Net Core!

Just wanted to ask you to update the repo URL for this resource, please https://github.com/mjebrahimi/Awesome-Microservices-NetCore#microservices-and-docker-with-net-core-and-azure-service-fabric to point to https://github.com/vany0114/microservices-dotnetcore-docker-sf-k8s because it's really more accurate.

Besides that, can you guys change the title **Microservices and Docker with .Net Core and Azure Service Fabric** to **Microservices and Docker with .Net Core and Azure Service Fabric/Kubernetes** since at the beginning of this year I refactored a lot of things and included support to K8s.

Thanks again guys!

**Comment by mjebrahimi** [comment]
@vany0114 Thanks for your interest.

I did it.

**Comment by vany0114** [comment]
Thanks, the link is not working just FYI
![image](https://user-images.githubusercontent.com/12032625/92152258-02006f80-ede8-11ea-970f-9527a97a54f8.png)
