### ISSUE TITLE
Serverless Event-Driven Architecture on Azure

### ISSUE THREAD

**Issue by p-bojkowski** [mjebrahimi/Awesome-Microservices-NetCore#7]
Hi!

you should add:

[Serverless Event-Driven Architecture on Azure: A Worked Example - Part 1](https://dev.to/mariomeyrelles/serverless-event-driven-architecture-on-azure-a-worked-example-part-1-481e)

[Serverless Event-Driven Architecture on Azure: A Worked Example - Part 2](https://dev.to/mariomeyrelles/serverless-event-driven-architecture-on-azure-a-worked-example-part-2-3im6)

this is from Mario Meyrelles:

https://github.com/mariomeyrelles
https://twitter.com/mariomeyrelles

**Comment by mjebrahimi** [comment]
Hi, done. a31cffa
