### ISSUE TITLE
Microservices from zero to hero

### ISSUE THREAD

**Issue by vitaly-pavluk** [mjebrahimi/Awesome-Microservices-NetCore#8]
Seems this set of articles is missing in the awesome list
[Microservice Series - From Zero to Hero](https://www.programmingwithwolfgang.com/microservice-series-from-zero-to-hero) 
It has pretty much comprehensive and short articles on how to create a microservice and deploy it to Azure Kubernetes.
Please add this to the awesome list if you consider articles useful.

**Comment by mjebrahimi** [comment]
Great articles!
Thank you. 
Done. https://github.com/mjebrahimi/Awesome-Microservices-NetCore/commit/fb97ac4cc975ff1e430a3bd4ca2e064f09b69a95
