### ISSUE TITLE
Add silky 

### ISSUE THREAD

**Issue by liuhll** [mjebrahimi/Awesome-Microservices-NetCore#9]
Silky is an aim to pass dotNet platform quickly constructs the framework of micro-service development. It has the characteristics of stability, safety, high performance, easy expansion and easy use.
- address: https://github.com/liuhll/silky

**Comment by mjebrahimi** [comment]
Great work. 
I gave it a star, but this project has just begun and it is not popular yet so I can not add it to this list at this time
